name: about_abe_2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  anabebe_packages:
    git:
      url: https://github.com/anabebe1020/anabebe_packages.git
      ref: master

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  google_fonts: ^3.0.1
  cloud_firestore: ^3.3.0
  firebase_core: ^1.19.2
  http: ^0.13.4
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SNSIcons
      fonts:
        - asset: assets/sns_icons.ttf