// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDylyna8Cz9PYhgOZHUabk9uCJyAlWRXoQ',
    appId: '1:829654777654:web:6799ac796eb35a8fcb3d97',
    messagingSenderId: '829654777654',
    projectId: 'i-am-abe',
    authDomain: 'i-am-abe.firebaseapp.com',
    storageBucket: 'i-am-abe.appspot.com',
    measurementId: 'G-1C9608F4QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjvxJxYG37eyEtjfsEMxsgfMtiGnWlCBs',
    appId: '1:829654777654:android:ba4a860df383b78bcb3d97',
    messagingSenderId: '829654777654',
    projectId: 'i-am-abe',
    storageBucket: 'i-am-abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxkQoS6LH1FV-6ixF81dEXKUaJV1oTUk',
    appId: '1:829654777654:ios:330c4e312c6c79a3cb3d97',
    messagingSenderId: '829654777654',
    projectId: 'i-am-abe',
    storageBucket: 'i-am-abe.appspot.com',
    iosClientId: '829654777654-5aab2qq539cljn58lik71mh14r18siof.apps.googleusercontent.com',
    iosBundleId: 'com.anabebe.aboutAbe2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxkQoS6LH1FV-6ixF81dEXKUaJV1oTUk',
    appId: '1:829654777654:ios:330c4e312c6c79a3cb3d97',
    messagingSenderId: '829654777654',
    projectId: 'i-am-abe',
    storageBucket: 'i-am-abe.appspot.com',
    iosClientId: '829654777654-5aab2qq539cljn58lik71mh14r18siof.apps.googleusercontent.com',
    iosBundleId: 'com.anabebe.aboutAbe2',
  );
}
